name:                boopadoop
version:             0.0.0.2
github:              "Lazersmoke/boopadoop"
license:             MIT
author:              "Sam Quinn"
maintainer:          "lazersmoke@gmail.com"
copyright:           "2019 Sam Quinn"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Mathematically sound sound synthesis
category:            Music

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Lazersmoke/boopadoop#readme>

dependencies:
- base >= 4.7 && < 5
- WAVE
- primes
- split
- semialign
- vector
- containers
- primitive
- aeson
- text
- bytestring
- fixed-vector
- random
- time
- serialport

library:
  source-dirs: 
  - src
  ghc-options:
  - -Wall
  c-sources: cbits/cstuff.cpp
  extra-libraries:
  - stdc++
  - ole32
  - rtaudio

executables:
  perfprof:
    main: Main.hs
    source-dirs: perfprof
    dependencies: boopadoop

tests:
  boopadoop-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - boopadoop
